spring:
  datasource:
    driver-class-name: org.sqlite.JDBC
#    url: jdbc:sqlite:D:\Workspaces\movie\src\main\resources\database\movie.db
    url: jdbc:sqlite:D:\Workspaces\movie.db
    username:
    password:

#  security:
#    user:
#      name: admin
#      password: admin
#      roles: admin

mybatis:
  mapper-locations: classpath*:/mapper/**.xml