spring:
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:D:\Workspaces\movie\src\main\resources\database\movie.db
    username:
    password:

mybatis:
  mapper-locations: classpath*:/mapper/**.xml