spring:
  datasource:
    driver-class-name: org.sqlite.JDBC
#    url: jdbc:sqlite:D:\Workspaces\movie\src\main\resources\database\movie.db
    url: jdbc:sqlite:D:\Workspaces\movie.db
    username:
    password:

#  security:
#    user:
#      name: admin
#      password: admin
#      roles: admin

mybatis:
  mapper-locations: classpath*:/mapper/**.xml

#swagger配置
swagger:
  headers:
    open: true
    params:
      - required: false
        name: authorization
        description: 认证

#自定义过滤路径
auth:
  basic-filter:
    accessUriList:
      - /auth/findAuthById
      - /login/webLogin
    accessPattenUriList:
      - /images/



